/* Learning content for the Today page. All facts are checked, non-fiction.
   Astrology entries describe the tradition, not scientific claims. Extend freely. */

const LEARN_CATEGORIES=[
  {id:'astronomy',label:'Astronomy'},
  {id:'astrology',label:'Astrology'},
  {id:'science',label:'Science (general)'},
  {id:'biology',label:'Biology'},
  {id:'chemistry',label:'Chemistry'},
  {id:'physics',label:'Physics'},
  {id:'maritime',label:'Maritime'},
  {id:'economics',label:'Economics'},
  {id:'sports',label:'Sports'},
  {id:'investing',label:'Investing'},
  {id:'history',label:'History'},
  {id:'scihistory',label:'Science history'},
  {id:'geography',label:'Geography'},
  {id:'technology',label:'Technology'},
  {id:'arts',label:'Arts & culture'},
  {id:'mathematics',label:'Mathematics'},
  {id:'nature',label:'Nature & environment'},
  {id:'psychology',label:'Psychology'},
];

const WORDS=[
  {w:'Ephemeral',def:'Lasting for a very short time.',ex:'Fame can be ephemeral.'},
  {w:'Ubiquitous',def:'Present, appearing, or found everywhere.',ex:'Smartphones are now ubiquitous.'},
  {w:'Serendipity',def:'The occurrence of finding something good without looking for it.',ex:'They met by pure serendipity.'},
  {w:'Pragmatic',def:'Dealing with things sensibly and practically.',ex:'A pragmatic approach to the budget.'},
  {w:'Gregarious',def:'Fond of company; sociable.',ex:'She has a gregarious personality.'},
  {w:'Eloquent',def:'Fluent or persuasive in speaking or writing.',ex:'An eloquent plea for peace.'},
  {w:'Resilient',def:'Able to recover quickly from difficulties.',ex:'Children are remarkably resilient.'},
  {w:'Meticulous',def:'Showing great attention to detail; very careful.',ex:'Meticulous record-keeping.'},
  {w:'Ambivalent',def:'Having mixed or contradictory feelings about something.',ex:'He felt ambivalent about moving.'},
  {w:'Candid',def:'Truthful and straightforward; frank.',ex:'A candid assessment of the risks.'},
  {w:'Nostalgia',def:'A sentimental longing for the past.',ex:'A wave of nostalgia hit her.'},
  {w:'Tenacious',def:'Holding firmly to something; persistent.',ex:'A tenacious negotiator.'},
  {w:'Voracious',def:'Wanting or consuming great quantities, especially of food or reading.',ex:'A voracious reader.'},
  {w:'Lucid',def:'Expressed clearly; easy to understand.',ex:'A lucid explanation.'},
  {w:'Benevolent',def:'Well meaning and kindly.',ex:'A benevolent smile.'},
  {w:'Cacophony',def:'A harsh, discordant mixture of sounds.',ex:'A cacophony of car horns.'},
  {w:'Diligent',def:'Showing careful and persistent effort.',ex:'A diligent student.'},
  {w:'Enigma',def:'A person or thing that is mysterious or puzzling.',ex:'Her motives remain an enigma.'},
  {w:'Frugal',def:'Sparing or economical with money or resources.',ex:'A frugal lifestyle.'},
  {w:'Idyllic',def:'Extremely happy, peaceful, or picturesque.',ex:'An idyllic seaside village.'},
  {w:'Juxtapose',def:'To place close together for contrasting effect.',ex:'The film juxtaposes wealth and poverty.'},
  {w:'Lethargic',def:'Sluggish and lacking in energy.',ex:'The heat left everyone lethargic.'},
  {w:'Mundane',def:'Lacking interest or excitement; ordinary.',ex:'The mundane details of daily life.'},
  {w:'Nuance',def:'A subtle difference in meaning, expression, or sound.',ex:'She caught every nuance of his tone.'},
  {w:'Obsolete',def:'No longer produced or used; out of date.',ex:'The technology is now obsolete.'},
  {w:'Placate',def:'To make someone less angry or hostile.',ex:'He tried to placate the crowd.'},
  {w:'Quaint',def:'Attractively unusual or old-fashioned.',ex:'A quaint little tea shop.'},
  {w:'Reticent',def:'Not revealing one’s thoughts readily; reserved.',ex:'He was reticent about his past.'},
  {w:'Sagacious',def:'Having or showing keen judgment; wise.',ex:'A sagacious piece of advice.'},
  {w:'Transient',def:'Lasting only for a short time; impermanent.',ex:'A transient population.'},
  {w:'Verbose',def:'Using or containing more words than needed.',ex:'A verbose report.'},
  {w:'Whimsical',def:'Playfully quaint or fanciful.',ex:'Whimsical illustrations.'},
  {w:'Zealous',def:'Having or showing great energy or enthusiasm.',ex:'A zealous supporter.'},
  {w:'Astute',def:'Having sharp judgment; shrewd.',ex:'An astute investor.'},
  {w:'Brevity',def:'Concise and exact use of words.',ex:'Valued for its brevity.'},
  {w:'Cogent',def:'Clear, logical, and convincing.',ex:'A cogent argument.'},
];

const FACTS=[
  {cat:'astronomy',text:'A day on Venus is longer than its year — it rotates once every ~243 Earth days but orbits the Sun every ~225.'},
  {cat:'astronomy',text:'A sugar-cube-sized amount of a neutron star would weigh about a billion tonnes.'},
  {cat:'astronomy',text:'The Sun accounts for about 99.86% of all the mass in the Solar System.'},
  {cat:'astronomy',text:'Sunlight takes roughly 8 minutes 20 seconds to travel from the Sun to Earth.'},
  {cat:'astrology',text:'In Western astrology the zodiac is split into 12 signs, each tied to one of four elements: fire, earth, air, or water.'},
  {cat:'astrology',text:'Because Earth’s axis slowly wobbles (precession), the constellations no longer line up with the zodiac dates set ~2,000 years ago.'},
  {cat:'astrology',text:'Astrology’s "retrograde" is when a planet appears to move backward — an optical effect of orbital speeds, not real reversal.'},
  {cat:'science',text:'Under some conditions hot water can freeze faster than cold — the Mpemba effect, still debated by scientists.'},
  {cat:'science',text:'Glass is an amorphous solid; old windows being thicker at the bottom is due to how they were made, not glass "flowing".'},
  {cat:'science',text:'Your body contains roughly as many bacterial cells as human cells.'},
  {cat:'biology',text:'Octopuses have three hearts and blue, copper-based blood.'},
  {cat:'biology',text:'Your stomach renews much of its lining every few days so it doesn’t digest itself.'},
  {cat:'biology',text:'Botanically, bananas are berries — but strawberries are not.'},
  {cat:'biology',text:'Tardigrades ("water bears") can survive the vacuum of space and extreme radiation.'},
  {cat:'chemistry',text:'Helium was detected in the Sun’s spectrum before it was ever found on Earth.'},
  {cat:'chemistry',text:'Water expands when it freezes, which is why ice floats — unusual among liquids.'},
  {cat:'chemistry',text:'Diamond and graphite are both pure carbon; only the bonding between atoms differs.'},
  {cat:'chemistry',text:'Gold and copper are the best-known metals that aren’t silvery-grey in colour.'},
  {cat:'physics',text:'Nothing with mass can reach light speed — its energy would have to become infinite.'},
  {cat:'physics',text:'Absolute zero (−273.15 °C) is the coldest possible temperature; it can be approached but never reached.'},
  {cat:'physics',text:'Time runs very slightly faster at your head than your feet, because gravity is weaker higher up.'},
  {cat:'physics',text:'A photon has no mass and always travels at the speed of light in a vacuum.'},
  {cat:'maritime',text:'"Port" and "starboard" are used instead of left/right because they don’t change with the way a sailor is facing.'},
  {cat:'maritime',text:'A knot is one nautical mile per hour — about 1.15 miles per hour.'},
  {cat:'maritime',text:'The Plimsoll line on a ship’s hull shows how heavily it may be safely loaded in different waters.'},
  {cat:'maritime',text:'Around 80% of world trade by volume is carried across the oceans by ship.'},
  {cat:'economics',text:'Opportunity cost is the value of the next best thing you give up when you make a choice.'},
  {cat:'economics',text:'During 1920s German hyperinflation, banknotes briefly became cheaper to burn than firewood.'},
  {cat:'economics',text:'GDP counts goods and services produced, but not unpaid work like housework or caregiving.'},
  {cat:'sports',text:'The marathon’s 42.195 km distance was fixed at the 1908 London Olympics.'},
  {cat:'sports',text:'The NBA didn’t add the three-point line until the 1979–80 season.'},
  {cat:'sports',text:'Golf balls have dimples (usually 300–500) because they cut drag and make the ball fly farther.'},
  {cat:'investing',text:'Compound interest means earning returns on your past returns — which is why starting early matters so much.'},
  {cat:'investing',text:'Diversification spreads money across assets to reduce risk without necessarily lowering expected return.'},
  {cat:'investing',text:'A market index like the S&P 500 tracks a basket of companies to represent the wider market.'},
  {cat:'history',text:'The Great Fire of London (1666) destroyed much of the city yet reportedly killed very few people.'},
  {cat:'history',text:'Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid.'},
  {cat:'history',text:'Teaching at Oxford began before the Aztec Empire was founded.'},
  {cat:'history',text:'The Berlin Wall stood from 1961 until it fell in 1989.'},
  {cat:'scihistory',text:'Newton and Leibniz developed calculus independently, sparking a bitter priority dispute.'},
  {cat:'scihistory',text:'Marie Curie is the only person to win Nobel Prizes in two different sciences — Physics and Chemistry.'},
  {cat:'scihistory',text:'The DNA double helix was described in 1953, drawing on Rosalind Franklin’s X-ray images.'},
  {cat:'scihistory',text:'Mendeleev built the periodic table so well he left gaps predicting elements not yet discovered.'},
  {cat:'geography',text:'Russia spans 11 time zones — more than any other country.'},
  {cat:'geography',text:'The Sahara is the largest hot desert, but Antarctica is the largest desert of all.'},
  {cat:'geography',text:'Everest is highest above sea level, but Mauna Kea is taller measured from its base on the seafloor.'},
  {cat:'geography',text:'Africa is the only continent that sits in all four hemispheres.'},
  {cat:'technology',text:'The first computer "bug" was a real moth found in a Harvard relay in 1947.'},
  {cat:'technology',text:'The QWERTY layout dates from the 1870s, partly to space out common letter pairs.'},
  {cat:'technology',text:'Ray Tomlinson chose the "@" symbol for email addresses in 1971.'},
  {cat:'mathematics',text:'A "googol" is 1 followed by 100 zeros — the company Google is named after a misspelling of it.'},
  {cat:'mathematics',text:'In a group of just 23 people there’s about a 50% chance two share a birthday.'},
  {cat:'mathematics',text:'Euclid proved over 2,000 years ago that the prime numbers never run out.'},
  {cat:'nature',text:'Honey never really spoils — edible honey has been found in ancient Egyptian tombs.'},
  {cat:'nature',text:'Lightning strikes the Earth several million times every day.'},
  {cat:'nature',text:'A mature tree can absorb tens of kilograms of carbon dioxide per year.'},
  {cat:'arts',text:'The Mona Lisa has no clearly visible eyebrows.'},
  {cat:'arts',text:'Shakespeare coined or popularised hundreds of English words still in use today.'},
  {cat:'arts',text:'"Origami" comes from the Japanese words oru (to fold) and kami (paper).'},
  {cat:'psychology',text:'The Dunning–Kruger effect describes how people with little skill often overestimate their ability.'},
  {cat:'psychology',text:'Your brain uses about 20% of your body’s energy while being only ~2% of its weight.'},
  {cat:'psychology',text:'Spaced repetition — reviewing over increasing intervals — is one of the most effective ways to learn.'},
];

const TOPICS=[
  {cat:'astronomy',title:'The life cycle of a star',blurb:'From a collapsing gas cloud to a white dwarf, neutron star, or black hole — how a star’s mass decides its fate.'},
  {cat:'astrology',title:'The history of the zodiac',blurb:'How ancient Babylonians carved the sky into twelve signs, and why the calendar dates have since drifted.'},
  {cat:'science',title:'What the scientific method really is',blurb:'How a hunch becomes a hypothesis, a theory, and why "just a theory" misunderstands the word.'},
  {cat:'biology',title:'How CRISPR gene editing works',blurb:'A bacterial defence system repurposed to edit DNA with remarkable precision.'},
  {cat:'chemistry',title:'Why the periodic table looks the way it does',blurb:'How the arrangement of electrons explains the table’s rows, columns, and patterns.'},
  {cat:'physics',title:'Relativity in plain terms',blurb:'Why time and space bend with speed and gravity — and what E = mc² is actually saying.'},
  {cat:'maritime',title:'How the shipping container changed the world',blurb:'A simple steel box that quietly rewired global trade and made goods cheap to move.'},
  {cat:'economics',title:'What actually causes inflation',blurb:'Demand, supply shocks, and the money supply — the forces behind rising prices.'},
  {cat:'sports',title:'The science of a curving free kick',blurb:'Spin, air pressure, and the Magnus effect that bends a football around the wall.'},
  {cat:'investing',title:'Index funds versus picking stocks',blurb:'Why so many investors favour low-cost funds that simply track the market.'},
  {cat:'history',title:'The Silk Road',blurb:'The ancient trade network that carried silk, ideas, religions — and disease — across continents.'},
  {cat:'scihistory',title:'The race to the DNA double helix',blurb:'Watson, Crick, Wilkins, and Franklin — the discovery that unlocked modern biology.'},
  {cat:'geography',title:'Why plate tectonics matters',blurb:'How drifting continents raise mountains, open oceans, and trigger earthquakes.'},
  {cat:'technology',title:'How the internet actually works',blurb:'Packets, protocols, and the surprising journey your data takes on a single click.'},
  {cat:'arts',title:'The Renaissance',blurb:'How a rebirth of art, science, and humanism reshaped Europe from the 14th century onward.'},
  {cat:'mathematics',title:'The golden ratio',blurb:'A single number that turns up in seashells, sunflowers, art, and architecture.'},
  {cat:'nature',title:'How coral reefs are built',blurb:'Tiny animals constructing the ocean’s most biodiverse ecosystems — and why they’re fragile.'},
  {cat:'psychology',title:'Cognitive biases',blurb:'The mental shortcuts that quietly steer your everyday decisions, often without you noticing.'},
];
